Repository assemblerflow/flowcraft, pull requests merged in 2018-07, with the labels that each got.

#104 Checkpoints clear
  flowcraft/generator/templates/fastqc_trimmomatic.nf
  flowcraft/generator/templates/skesa.nf
  flowcraft/generator/templates/spades.nf
  flowcraft/generator/templates/trimmomatic.nf
  flowcraft/nextflow.config
  flowcraft/templates/skesa.py
  flowcraft/templates/spades.py
  flowcraft/templates/trimmomatic.py
Labels: enhancement

#109 Patlas update dbs
  changelog.md
  flowcraft/generator/components/patlas_mapping.py
  flowcraft/generator/templates/mapping_patlas.nf
  flowcraft/generator/templates/mash_dist.nf
  flowcraft/generator/templates/mash_screen.nf
  flowcraft/nextflow.config
  flowcraft/templates/mapping2json.py
  flowcraft/templates/mashdist2json.py
  flowcraft/templates/mashscreen2json.py
  flowcraft/templates/pATLAS_consensus_json.py
Labels: enhancement, reports

#110 added new component fasterq-dump to flowcraft
  changelog.md
  docs/user/available_components.rst
  docs/user/components/fasterq_dump.rst
  docs/user/components/reads_download.rst
  flowcraft/generator/components/downloads.py
  flowcraft/generator/engine.py
  flowcraft/generator/header_skeleton.py
  flowcraft/generator/templates/fasterq_dump.nf
  flowcraft/generator/templates/mash_screen.nf
Labels: enhancement, process

#112 add Mash sketch for fastq and fasta files
  changelog.md
  docs/user/available_components.rst
  docs/user/components/mapping_patlas.rst
  docs/user/components/mash_dist.rst
  docs/user/components/mash_screen.rst
  docs/user/components/mash_sketch_fasta.rst
  docs/user/components/mash_sketch_fastq.rst
  flowcraft/generator/components/distance_estimation.py
  flowcraft/generator/engine.py
  flowcraft/generator/templates/mash_dist.nf
  flowcraft/generator/templates/mash_screen.nf
  flowcraft/generator/templates/mash_sketch_fasta.nf
  flowcraft/generator/templates/mash_sketch_fastq.nf
Labels: process

#116 Added momps component
  flowcraft/generator/components/typing.py
  flowcraft/generator/engine.py
  flowcraft/generator/templates/momps.nf
Labels: process

#115 Added subsampling component
  docs/user/available_components.rst
  docs/user/components/sample_fastq.rst
  flowcraft/generator/components/reads_quality_control.py
  flowcraft/generator/engine.py
  flowcraft/generator/templates/sample_fastq.nf
  flowcraft/templates/sample_fastq.py
Labels: process
