Repository assemblerflow/flowcraft, pull requests merged in 2018-03, with the labels that each got.

#22 Implemented status/log collection process. #19 #21
  assemblerflow/generator/engine.py
  assemblerflow/generator/process.py
  assemblerflow/generator/templates/abricate.nf
  assemblerflow/generator/templates/assembly_mapping.nf
  assemblerflow/generator/templates/check_coverage.nf
  assemblerflow/generator/templates/chewbbaca.nf
  assemblerflow/generator/templates/compiler_channels.txt
  assemblerflow/generator/templates/fastqc.nf
  assemblerflow/generator/templates/fastqc_trimmomatic.nf
  assemblerflow/generator/templates/integrity_coverage.nf
  assemblerflow/generator/templates/mlst.nf
  assemblerflow/generator/templates/patho_typing.nf
  assemblerflow/generator/templates/pilon.nf
  assemblerflow/generator/templates/process_spades.nf
  assemblerflow/generator/templates/prokka.nf
  assemblerflow/generator/templates/seq_typing.nf
  assemblerflow/generator/templates/skesa.nf
  assemblerflow/generator/templates/spades.nf
  assemblerflow/generator/templates/status_compiler.nf
  assemblerflow/generator/templates/trimmomatic.nf
Labels: core, enhancement

#28 Added option to run chewbbaca with ExtractCgMLST
  assemblerflow/generator/templates/chewbbaca.nf
  assemblerflow/nextflow.config
Labels: enhancement, process

#34 DAG tool
  assemblerflow/generator/engine.py
  assemblerflow/generator/templates/pipeline_graph.html
  assemblerflow/tests/test_assemblerflow.py
Labels: enhancement
