Repository assemblerflow/flowcraft, pull requests merged in 2018-11, with the labels that each got.

#166 Skesa update
  changelog.md
  docs/user/components/skesa.rst
  flowcraft/generator/components/assembly.py
Labels: Components

#165 Container versioning
  changelog.md
  flowcraft/generator/process_details.py
Labels: enhancement

#160 added timestamp to report and inspect
  changelog.md
  flowcraft/generator/inspect.py
  flowcraft/generator/report.py
Labels: enhancement

#161 Diamond
  changelog.md
  docs/user/components/diamond.rst
  flowcraft/generator/components/annotation.py
  flowcraft/generator/engine.py
  flowcraft/generator/templates/diamond.nf
Labels: Components

#167 Dockerhub tags
  changelog.md
  flowcraft/flowcraft.py
  flowcraft/generator/engine.py
  flowcraft/generator/process_details.py
Labels: enhancement

#162 Automatic processes
  changelog.md
  docs/dev/create_process.rst
  flowcraft/flowcraft.py
  flowcraft/generator/components/assembly.py
  flowcraft/generator/components/distance_estimation.py
  flowcraft/generator/components/downloads.py
  flowcraft/generator/components/mapping.py
  flowcraft/generator/components/metagenomics.py
  flowcraft/generator/components/mlst.py
  flowcraft/generator/components/patlas_mapping.py
  flowcraft/generator/components/reads_quality_control.py
  flowcraft/generator/engine.py
  flowcraft/generator/process_collector.py
  flowcraft/tests/test_engine.py
  flowcraft/tests/test_pipeline_parser.py
  flowcraft/tests/test_process_details.py
  flowcraft/tests/test_processes.py
  setup.py
Labels: engine, enhancement

#171 fixed #170
  changelog.md
  flowcraft/generator/engine.py
Labels: bug

#172 fix bug in momps
  changelog.md
  flowcraft/generator/templates/momps.nf
Labels: Components
