Repository assemblerflow/flowcraft, pull requests merged in 2018-12, with the labels that each got.

#179 DEN-IM recipe 2.0
  changelog.md
  flowcraft/bin/parse_fasta.py
  flowcraft/generator/components/alignment.py
  flowcraft/generator/components/typing.py
  flowcraft/generator/recipes/denim.py
  flowcraft/generator/templates/bowtie.nf
  flowcraft/generator/templates/dengue_typing.nf
  flowcraft/generator/templates/mafft.nf
  flowcraft/generator/templates/viral_assembly.nf
Labels: enhancement

#183 Fix search for nextflow run command in .nextflow.log
  changelog.md
  flowcraft/generator/inspect.py
  flowcraft/generator/report.py
Labels: bufix

#184 PR to accommodate comments on #183
  flowcraft/flowcraft.py
  flowcraft/generator/error_handling.py
  flowcraft/generator/inspect.py
  flowcraft/generator/report.py
  flowcraft/generator/utils.py
  flowcraft/tests/broadcast_tests/empty_log.txt
  flowcraft/tests/broadcast_tests/log_with_command.txt
  flowcraft/tests/broadcast_tests/log_without_command.txt
  flowcraft/tests/test_broadcast.py
Labels: enhancement, inspect, reports

#187 Add manifest scope to the pipeline config
  changelog.md
  flowcraft/generator/engine.py
  flowcraft/generator/templates/manifest.config
  flowcraft/nextflow.config
  flowcraft/tests/test_assemblerflow.py
Labels: enhancement
